#!/usr/bin/env node

/**
 * Dew Icons — build.js
 * Reads src/icons/*.svg → generates dist/dew.css and preview/index.html
 */

const fs = require('fs');
const path = require('path');

const SRC_DIR  = path.join(__dirname, '../src/icons');
const DIST_DIR = path.join(__dirname, '../dist');
const PREV_DIR = path.join(__dirname, '../preview');

[DIST_DIR, PREV_DIR].forEach(dir => {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
});

// ── 1. Read all SVG files ──────────────────────────────────────────────────

const svgFiles = fs.readdirSync(SRC_DIR)
  .filter(f => f.endsWith('.svg'))
  .sort();

if (svgFiles.length === 0) {
  console.error('No SVG files found in src/icons/');
  process.exit(1);
}

console.log(`Found ${svgFiles.length} icons:`);

const icons = svgFiles.map(filename => {
  const name    = filename.replace('.svg', '');
  const content = fs.readFileSync(path.join(SRC_DIR, filename), 'utf8').trim();
  console.log(`  ✓ ${name}`);
  return { name, filename, content };
});

// ── 2. Encode SVG for CSS data URI ────────────────────────────────────────

function svgToDataUrl(svgContent) {
  return 'data:image/svg+xml,' + svgContent
    .replace(/\n\s*/g, ' ')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/\s+/g, ' ')
    .replace(/"/g, "'")
    .replace(/%/g, '%25')
    .replace(/#/g, '%23')
    .replace(/</g, '%3C')
    .replace(/>/g, '%3E')
    .trim();
}

// ── 3. Build CSS ──────────────────────────────────────────────────────────

const cssLines = [
  '/* Dew Icons — generated by scripts/build.js */',
  '/* https://github.com/FAMKIND/dew */',
  '',
  '.dew {',
  '  display: inline-block;',
  '  width: 1.5em;',
  '  height: 1.5em;',
  '  background-color: currentColor;',
  '  -webkit-mask-size: contain;',
  '  mask-size: contain;',
  '  -webkit-mask-repeat: no-repeat;',
  '  mask-repeat: no-repeat;',
  '  -webkit-mask-position: center;',
  '  mask-position: center;',
  '  vertical-align: middle;',
  '  flex-shrink: 0;',
  '}',
  '',
];

icons.forEach(icon => {
  const dataUrl = svgToDataUrl(icon.content);
  cssLines.push(
    `/* ${icon.name} */`,
    `.dew-${icon.name} {`,
    `  -webkit-mask-image: url("${dataUrl}");`,
    `  mask-image: url("${dataUrl}");`,
    `}`,
    '',
  );
});

const cssOutput = cssLines.join('\n');
fs.writeFileSync(path.join(DIST_DIR, 'dew.css'), cssOutput);
console.log(`\nGenerated dist/dew.css (${Math.round(cssOutput.length / 1024)}KB)`);

// ── 4. Build preview/index.html ───────────────────────────────────────────

const SIZES = [16, 24, 32, 48];

const iconGrid = icons.map(icon => {
  const sizeBlocks = SIZES.map(size => {
    // Inject explicit size into the SVG for preview
    const sized = icon.content
      .replace(/width="[^"]*"/, `width="${size}"`)
      .replace(/height="[^"]*"/, `height="${size}"`);

    return `
    <div class="size-block">
      <span class="size-label">${size}</span>
      <div class="icon-demo">${sized}</div>
    </div>`;
  }).join('');

  return `
  <div class="icon-card">
    <div class="icon-name">${icon.name}</div>
    <div class="sizes-row">${sizeBlocks}</div>
  </div>`;
}).join('\n');

const previewHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Dew Icons — Visual Catalog</title>
  <style>
    :root {
      --bg: #ffffff;
      --bg2: #f5f5f5;
      --border: #e0e0e0;
      --text: #111111;
      --text2: #666666;
      --icon: #111111;
      --accent: #007aff;
    }
    [data-theme="dark"] {
      --bg: #111111;
      --bg2: #1c1c1c;
      --border: #2e2e2e;
      --text: #f0f0f0;
      --text2: #888888;
      --icon: #f0f0f0;
    }
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: var(--bg);
      color: var(--text);
      transition: background 0.2s, color 0.2s;
    }
    header {
      padding: 20px 28px;
      border-bottom: 1px solid var(--border);
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 16px;
      flex-wrap: wrap;
    }
    .header-left h1 { font-size: 18px; font-weight: 600; letter-spacing: -0.3px; }
    .header-left p  { font-size: 12px; color: var(--text2); margin-top: 3px; }
    .header-left a  { color: var(--accent); text-decoration: none; }
    .controls { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }
    button {
      padding: 5px 12px;
      border: 1px solid var(--border);
      background: var(--bg2);
      color: var(--text);
      border-radius: 6px;
      font-size: 12px;
      cursor: pointer;
    }
    button:hover { background: var(--border); }
    .swatches { display: flex; gap: 5px; }
    .swatch {
      width: 24px; height: 24px;
      border-radius: 5px;
      border: 1px solid var(--border);
      cursor: pointer;
    }
    .swatch:hover { transform: scale(1.1); }
    main { padding: 28px; }
    .stats { font-size: 12px; color: var(--text2); margin-bottom: 20px; }
    .icon-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(360px, 1fr));
      gap: 1px;
      background: var(--border);
      border: 1px solid var(--border);
      border-radius: 8px;
      overflow: hidden;
    }
    .icon-card {
      background: var(--bg);
      padding: 14px 16px;
      display: flex;
      flex-direction: column;
      gap: 10px;
    }
    .icon-name {
      font-size: 11px;
      font-weight: 600;
      font-family: 'SF Mono', 'Fira Code', 'Menlo', monospace;
      color: var(--text2);
    }
    .sizes-row { display: flex; gap: 20px; align-items: flex-end; flex-wrap: wrap; }
    .size-block { display: flex; flex-direction: column; align-items: center; gap: 5px; }
    .size-label { font-size: 10px; color: var(--text2); font-family: monospace; }
    .icon-demo {
      display: flex;
      align-items: center;
      justify-content: center;
      color: var(--icon);
    }
    .icon-demo svg { display: block; color: inherit; }
    footer {
      padding: 20px 28px;
      border-top: 1px solid var(--border);
      font-size: 12px;
      color: var(--text2);
      display: flex;
      gap: 16px;
      flex-wrap: wrap;
    }
    footer a { color: var(--accent); text-decoration: none; }
  </style>
</head>
<body>
  <header>
    <div class="header-left">
      <h1>Dew Icons</h1>
      <p>Icon library for <a href="https://github.com/FAMKIND/seed">Seed</a> by <a href="https://famkind.com">FAMKIND</a> &mdash; ${icons.length} icons</p>
    </div>
    <div class="controls">
      <div class="swatches">
        <div class="swatch" style="background:#111" title="Black" onclick="setColor('#111')"></div>
        <div class="swatch" style="background:#007aff" title="Blue" onclick="setColor('#007aff')"></div>
        <div class="swatch" style="background:#ff3b30" title="Red" onclick="setColor('#ff3b30')"></div>
        <div class="swatch" style="background:#34c759" title="Green" onclick="setColor('#34c759')"></div>
        <div class="swatch" style="background:#ff9500" title="Orange" onclick="setColor('#ff9500')"></div>
        <div class="swatch" style="background:#af52de" title="Purple" onclick="setColor('#af52de')"></div>
      </div>
      <button onclick="toggleTheme()" id="theme-btn">Dark mode</button>
    </div>
  </header>
  <main>
    <p class="stats">${icons.length} icons &times; 4 sizes (16&thinsp;/&thinsp;24&thinsp;/&thinsp;32&thinsp;/&thinsp;48px) &mdash; all icons use <code>currentColor</code></p>
    <div class="icon-grid">
${iconGrid}
    </div>
  </main>
  <footer>
    <span>&copy; FAMKIND</span>
    <a href="https://famkind.com">famkind.com</a>
    <a href="https://github.com/FAMKIND/dew">github.com/FAMKIND/dew</a>
    <a href="https://github.com/FAMKIND/seed">Seed CSS</a>
    <a href="../DESIGN_SYSTEM.md">Design System</a>
    <a href="../STYLE_ANALYSIS.md">Style Analysis</a>
  </footer>
  <script>
    let dark = false;
    function toggleTheme() {
      dark = !dark;
      document.documentElement.setAttribute('data-theme', dark ? 'dark' : '');
      document.getElementById('theme-btn').textContent = dark ? 'Light mode' : 'Dark mode';
      setColor(dark ? '#f0f0f0' : '#111');
    }
    function setColor(c) {
      document.querySelectorAll('.icon-demo').forEach(el => el.style.color = c);
    }
  </script>
</body>
</html>`;

fs.writeFileSync(path.join(PREV_DIR, 'index.html'), previewHtml);
console.log(`Generated preview/index.html`);
console.log(`\nDone! ${icons.length} icons. Run: open preview/index.html`);
