#!/usr/bin/env node

/**
 * Dew Icons — build.js
 * Reads src/icons/*.svg → generates dist/dew.css and preview/index.html
 */

const fs = require('fs');
const path = require('path');

const SRC_DIR  = path.join(__dirname, '../src/icons');
const DIST_DIR = path.join(__dirname, '../dist');
const PREV_DIR = path.join(__dirname, '../preview');

// Ensure output dirs exist
[DIST_DIR, PREV_DIR].forEach(dir => {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
});

// ── 1. Read all SVG files ──────────────────────────────────────────────────

const svgFiles = fs.readdirSync(SRC_DIR)
  .filter(f => f.endsWith('.svg'))
  .sort();

if (svgFiles.length === 0) {
  console.error('No SVG files found in src/icons/');
  process.exit(1);
}

console.log(`Found ${svgFiles.length} icons:`);

const icons = svgFiles.map(filename => {
  const name    = filename.replace('.svg', '');
  const content = fs.readFileSync(path.join(SRC_DIR, filename), 'utf8');

  // Extract outline group content
  const outlineMatch = content.match(/<g[^>]*id="outline"[^>]*>([\s\S]*?)<\/g>/);
  const fillMatch    = content.match(/<g[^>]*id="fill"[^>]*>([\s\S]*?)<\/g>/);

  const outlineContent = outlineMatch ? outlineMatch[1].trim() : '';
  const fillContent    = fillMatch    ? fillMatch[1].trim()    : '';

  console.log(`  ✓ ${name}`);

  return { name, filename, content, outlineContent, fillContent };
});

// ── 2. Build CSS (mask-image approach for currentColor inheritance) ─────────

function svgToDataUrl(svgContent) {
  // Minimal encode: just handle the critical characters for data URIs
  return 'data:image/svg+xml,' + svgContent
    .replace(/\n\s*/g, ' ')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/\s+/g, ' ')
    .replace(/"/g, "'")
    .replace(/%/g, '%25')
    .replace(/#/g, '%23')
    .replace(/</g, '%3C')
    .replace(/>/g, '%3E')
    .trim();
}

function buildOutlineSvg(icon) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${icon.outlineContent}</g></svg>`;
}

function buildFillSvg(icon) {
  // For fill variant, use the fill group content but ensure currentColor is used
  // The fill SVG wraps content with no extra stroke defaults (each element handles its own)
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">${icon.fillContent}</svg>`;
}

const cssLines = [
  '/* Dew Icons — generated by scripts/build.js */',
  '/* https://github.com/FAMKIND/dew */',
  '',
  '.dew {',
  '  display: inline-block;',
  '  width: 1.5em;',
  '  height: 1.5em;',
  '  background-color: currentColor;',
  '  -webkit-mask-size: contain;',
  '  mask-size: contain;',
  '  -webkit-mask-repeat: no-repeat;',
  '  mask-repeat: no-repeat;',
  '  -webkit-mask-position: center;',
  '  mask-position: center;',
  '  vertical-align: middle;',
  '  flex-shrink: 0;',
  '}',
  '',
];

icons.forEach(icon => {
  const outlineUrl = svgToDataUrl(buildOutlineSvg(icon));
  const fillUrl    = svgToDataUrl(buildFillSvg(icon));

  cssLines.push(
    `/* ${icon.name} */`,
    `.dew-${icon.name} {`,
    `  -webkit-mask-image: url("${outlineUrl}");`,
    `  mask-image: url("${outlineUrl}");`,
    `}`,
    `.dew-${icon.name}-fill {`,
    `  -webkit-mask-image: url("${fillUrl}");`,
    `  mask-image: url("${fillUrl}");`,
    `}`,
    '',
  );
});

const cssOutput = cssLines.join('\n');
fs.writeFileSync(path.join(DIST_DIR, 'dew.css'), cssOutput);
console.log(`\nGenerated dist/dew.css (${Math.round(cssOutput.length / 1024)}KB)`);

// ── 3. Build preview/index.html ────────────────────────────────────────────

const iconGrid = icons.map(icon => {
  const sizes = [16, 24, 32, 48];

  const sizeBlocks = sizes.map(size => `
    <div class="size-block">
      <span class="size-label">${size}</span>
      <div class="icon-pair">
        <div class="icon-demo" title="${icon.name} outline">
          ${icon.content
            .replace(/<g[^>]*id="fill"[^>]*>[\s\S]*?<\/g>/, '')
            .replace(/style="display:none"/, '')
            .replace(/width="24"/, `width="${size}"`)
            .replace(/height="24"/, `height="${size}"`)
          }
        </div>
        <div class="icon-demo" title="${icon.name} fill">
          ${icon.content
            .replace(/<g[^>]*id="outline"[^>]*>[\s\S]*?<\/g>/, '')
            .replace(/style="display:none"/, '')
            .replace(/width="24"/, `width="${size}"`)
            .replace(/height="24"/, `height="${size}"`)
          }
        </div>
      </div>
    </div>`).join('');

  return `
  <div class="icon-card">
    <div class="icon-name">${icon.name}</div>
    <div class="sizes-row">${sizeBlocks}</div>
  </div>`;
}).join('\n');

const previewHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Dew Icons — Visual Catalog</title>
  <style>
    :root {
      --bg: #ffffff;
      --bg2: #f5f5f5;
      --border: #e0e0e0;
      --text: #111111;
      --text2: #666666;
      --icon-color: #111111;
      --accent: #007aff;
    }
    [data-theme="dark"] {
      --bg: #111111;
      --bg2: #1e1e1e;
      --border: #2e2e2e;
      --text: #f0f0f0;
      --text2: #888888;
      --icon-color: #f0f0f0;
    }
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: var(--bg);
      color: var(--text);
      min-height: 100vh;
      transition: background 0.2s, color 0.2s;
    }
    header {
      padding: 24px 32px;
      border-bottom: 1px solid var(--border);
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 16px;
      flex-wrap: wrap;
    }
    .header-left h1 { font-size: 20px; font-weight: 600; letter-spacing: -0.3px; }
    .header-left p  { font-size: 13px; color: var(--text2); margin-top: 2px; }
    .controls { display: flex; gap: 8px; align-items: center; }
    button {
      padding: 6px 14px;
      border: 1px solid var(--border);
      background: var(--bg2);
      color: var(--text);
      border-radius: 6px;
      font-size: 13px;
      cursor: pointer;
      transition: background 0.15s;
    }
    button:hover { background: var(--border); }
    .color-swatches { display: flex; gap: 6px; }
    .swatch {
      width: 28px; height: 28px;
      border-radius: 6px;
      border: 1px solid var(--border);
      cursor: pointer;
      transition: transform 0.1s;
    }
    .swatch:hover { transform: scale(1.1); }
    main { padding: 32px; }
    .stats {
      font-size: 12px;
      color: var(--text2);
      margin-bottom: 24px;
    }
    .icon-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(340px, 1fr));
      gap: 1px;
      background: var(--border);
      border: 1px solid var(--border);
      border-radius: 8px;
      overflow: hidden;
    }
    .icon-card {
      background: var(--bg);
      padding: 16px;
      display: flex;
      flex-direction: column;
      gap: 12px;
    }
    .icon-name {
      font-size: 12px;
      font-weight: 600;
      font-family: 'SF Mono', 'Fira Code', monospace;
      color: var(--text2);
      letter-spacing: 0.3px;
    }
    .sizes-row {
      display: flex;
      gap: 16px;
      align-items: flex-end;
      flex-wrap: wrap;
    }
    .size-block {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 6px;
    }
    .size-label {
      font-size: 10px;
      color: var(--text2);
      font-family: monospace;
    }
    .icon-pair {
      display: flex;
      gap: 6px;
      align-items: center;
    }
    .icon-demo {
      display: flex;
      align-items: center;
      justify-content: center;
      color: var(--icon-color);
    }
    .icon-demo svg {
      display: block;
      color: inherit;
    }
    footer {
      padding: 24px 32px;
      border-top: 1px solid var(--border);
      font-size: 12px;
      color: var(--text2);
      display: flex;
      gap: 16px;
      flex-wrap: wrap;
    }
    footer a { color: var(--accent); text-decoration: none; }
    footer a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <header>
    <div class="header-left">
      <h1>Dew Icons</h1>
      <p>The icon library for <a href="https://github.com/FAMKIND/seed" style="color:var(--accent)">Seed</a> by FAMKIND — ${icons.length} icons, outline &amp; fill variants</p>
    </div>
    <div class="controls">
      <div class="color-swatches">
        <div class="swatch" style="background:#111111" onclick="setColor('#111111')" title="Black"></div>
        <div class="swatch" style="background:#007aff" onclick="setColor('#007aff')" title="Blue"></div>
        <div class="swatch" style="background:#ff3b30" onclick="setColor('#ff3b30')" title="Red"></div>
        <div class="swatch" style="background:#34c759" onclick="setColor('#34c759')" title="Green"></div>
        <div class="swatch" style="background:#ff9500" onclick="setColor('#ff9500')" title="Orange"></div>
      </div>
      <button onclick="toggleTheme()" id="theme-btn">Dark mode</button>
    </div>
  </header>
  <main>
    <p class="stats">${icons.length} icons × 2 variants (outline + fill) × 4 sizes (16, 24, 32, 48px)</p>
    <div class="icon-grid">
      ${iconGrid}
    </div>
  </main>
  <footer>
    <span>© FAMKIND</span>
    <a href="https://famkind.com">famkind.com</a>
    <a href="https://github.com/FAMKIND/dew">github.com/FAMKIND/dew</a>
    <a href="https://github.com/FAMKIND/seed">Seed CSS Framework</a>
    <a href="../DESIGN_SYSTEM.md">Design System</a>
  </footer>
  <script>
    function toggleTheme() {
      const dark = document.documentElement.getAttribute('data-theme') === 'dark';
      document.documentElement.setAttribute('data-theme', dark ? '' : 'dark');
      document.getElementById('theme-btn').textContent = dark ? 'Dark mode' : 'Light mode';
      if (!dark) {
        // When switching to dark, update default icon swatch color
        setColor('#f0f0f0');
      } else {
        setColor('#111111');
      }
    }
    function setColor(color) {
      document.querySelectorAll('.icon-demo').forEach(el => {
        el.style.color = color;
      });
    }
  </script>
</body>
</html>`;

fs.writeFileSync(path.join(PREV_DIR, 'index.html'), previewHtml);
console.log(`Generated preview/index.html`);
console.log(`\nDone! Run: open preview/index.html`);
